### ISSUE TITLE
Build failing since abd5b6a8e44abeef4ecdfb57c899605756902edf

### ISSUE THREAD

**Issue by srslynow** [naibaf7/caffe#38]
conv_layer_spatial.cpp fails to build since commit:
abd5b6a8e44abeef4ecdfb57c899605756902edf (7 days ago)

Using master branch before this commit works.

Used configuration:
Makefile:
Cuda: 7.5
cuDNN: v5.0
Blas: open
No greentea/opencl

Hardware:
K20m GPU
16 core intel v3 xeon

Libraries used:
According to official installation instructions

**Comment by naibaf7** [comment]
@srslynow 
conv_layer_spatial is intended for Intel iGPUs only. This can be ignored, however I will exclude this test/layer on non-Intel platforms in the future.
