### ISSUE TITLE
When I use GPU, I get "Check failed:  Check failed: status == CUDNN_STATUS_SUCCESS(1 vs. 0)". When I use CPU, I get :" Check failed: status == CUBLAS_STATUS_SUCCESS(1 vs. 0)"

### ISSUE THREAD

**Issue by yuyadanyadan** [naibaf7/caffe#47]
Hi, I use caffe to train for a regression issue. The input are images without labels, while the output are images. Where is the problem? and I don't know whether my network is OK!

**Comment by yuyadanyadan** [comment]
And my graphic card is GTX 960. It can support compute capability 3.0 and higher.
My cudnn is 5.0, while my cuda is 8.0

**Comment by naibaf7** [comment]
Did you try with normal Caffe? This is OpenCL Caffe, and if you only use CUDA you won't get that many benefits from it anyways.

**Comment by yuyadanyadan** [comment]
Hi,
I use normal caffe!
Because I think you are familiar with caffe, I ask you!
No one else can discuss it with me.
I use GPU(include cuda and cudnn).
I think that it may be my net!
can you help me to watch my net?
Thank you !

在 2016-09-12 20:26:18，"Fabian Tschopp" notifications@github.com 写道：

Did you try with normal Caffe? This is OpenCL Caffe, and if you only use CUDA you won't get that many benefits from it anyways.

**Comment by naibaf7** [comment]
Sorry, I don't have time for doing non-bug user questions, and I am only responsible for the OpenCL code.

**Comment by yuyadanyadan** [comment]
Ok, thank you so much!
