### ISSUE TITLE
are fpga supported such as xilinx and altera boards? 

### ISSUE THREAD

**Issue by amoussawi** [naibaf7/caffe#49]
Hello. 
are fpga supported such as xilinx and altera boards? or has anyone tested it on an fpga? specifically for acceleration purpose.

**Comment by bhack** [comment]
https://github.com/dicecco1/fpga_caffe

**Comment by amoussawi** [comment]
thanks. I already looked at this. but I was just checking if this official work specifically is supported on fpga.

**Comment by naibaf7** [comment]
@abdallah95 
No, it's not; FPGAs need quite different methodologies than GPUs.
