### ISSUE TITLE
Mali GPU does not support host unified memory in fact 

### ISSUE THREAD

**Issue by DVEfremov** [naibaf7/caffe#53]
Step to reproduce:
1) Apply PR #50 and PR #51 based on opencl branch to get android version of caffe binary with required libs 

2) run caffe time comand and got error 
```

``` 
and strange artifacts on the screen while processing caffe command atleast for Galaxy Note 4 with Mali GPU:
```
I0202 16:24:37.476721  5890 common.cpp:405] Device id:                     0
I0202 16:24:37.476784  5890 common.cpp:407] Device backend:                OpenCL
I0202 16:24:37.476850  5890 common.cpp:409] Backend details:               ARM: OpenCL 1.1 
I0202 16:24:37.476951  5890 common.cpp:411] Device vendor:                 ARM
I0202 16:24:37.477020  5890 common.cpp:413] Name:                          Mali-T760
I0202 16:24:37.477088  5890 common.cpp:415] Total global memory:           2147483648
```

So as solution provide compilation param 
DISABLE_DEVICE_HOST_UNIFIED_MEMORY
to force disabling support host unified memory

**Comment by DVEfremov** [comment]
https://github.com/naibaf7/caffe/pull/54
merged to master so closing.

**Comment by bhack** [comment]
But is Mali requiring [CL_MEM_ALLOC_HOST_PTR](http://malideveloper.arm.com/downloads/deved/tutorial/SDK/opencl/memory_buffers_tutorial.html) ?

**Comment by bhack** [comment]
@naibaf7 https://github.com/naibaf7/libdnn/issues/17
