### ISSUE TITLE
Compilation fails for caffe opencl branch in CPU_ONLY mode

### ISSUE THREAD

**Issue by DVEfremov** [naibaf7/caffe#55]
Compilation fails for caffe opencl branch in CPU_ONLY mode
Just one missed 
```#ifdef USE_GREENTEA```

I've got fix. Will prepare PR soon.

**Comment by psyhtest** [comment]
@DVEfremov It seems that the fix has gone in. Can this be closed now?

**Comment by DVEfremov** [comment]
Yes it works, and merged already to opencl branch.
Thanks
