### ISSUE TITLE
Build error of file permission

### ISSUE THREAD

**Issue by WatorVapor** [naibaf7/caffe#6]
$(CL_KERNELS_SH)  has no permission problem.
## diff
# Copy the OpenCL kernels into C++ char strings

 $(CL_KERNELS_CPP) : $(CL_HEADERS) $(CL_KERNELS)
-   chmod +x $(CL_KERNELS_SH)
  $(CL_KERNELS_SH)
  
  proto: $(PROTO_GEN_CC) $(PROTO_GEN_HEADER)

**Comment by naibaf7** [comment]
Ok, good!
Note that this will be changed soon (or later) anyways, removing the need for the script.

**Comment by naibaf7** [comment]
Should be fixed in the latest version.
